language: go
go:
- tip
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get -t -v ./...
script:
- go test -v -race -cover -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN
notifications:
  email: false
env:
  secure: YbAS+IuIUaNwdT/J5Ww1MyUuyx+V+T1Zidf314G+LuM1Gp8H+5dthaznk+5IaOoHFDFMl2b0qtock7dokBnFDD12ngoTAdZdihAlnKlhpjy1yUfivDHjn3vSdpAaccCyperxHCbpkDbG0+DUEvpCf9h/91SImM3INkOyEWuwZ/oGBviblbcFSHJ+QrvxA/TELMBEfkhnjOQ3jdxFkdf70CRi0Xl5lYYg4G22NhSxnyxegdn46KLaO8Uixs3e7Bn/SUU6QZNQia7iisD+FtN7uE6eBfajehiHPczd/h/9veECI+51dto8FXPIimZzW9bPvbGAdselI0jrNuTnYAiydKhPSmAxS9IGvtUw/P9MQFgJtfQfNQ7Iq6blqigZrGHujJxOt3tgWlSOzeD0Z69F+BkyBxWMqDXwf05loluR/tF/ak4AME9/Z05KFVxasn6j/ukgleb97CZfUTiT5i8SCuwq3/3LQG0gzZBMSSFQk9ocQDmWublKWms9sAiZw8Pf4CgMLVQqB5yXBeJjEoELUE0IAS8GVbEJHOk60jU4qO/7UmM75fAUcEKSLx11zhnz7aV5fDrMh7/1d7tb15l/xnvsErwwI/TudSGnBiSdwb4XCKiC1Z1/bcmmd2/xIVU17+Vea2We9++dertHGz75PO61KcZRNZ5Ic84tC00DUps=
