language: go
go:
- tip
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get -t -v ./...
script:
- go test -v -race -cover -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN
notifications:
  email: false
env:
  secure: ew9oMG6Y1+DlqjZ/GoSgJnL5WWpRWEf5uLQatubUGqIP7GCcq6v3ag2C92/I80DKwGh6kGYRN/y9nHrSUGIqE2UhOY6m5vU0EccQFVzVjyo3BiDFjjTyzwG4R/+u+JMyHp0JEV8ujlsDiGfty0vtWfSsBZFEW3Id8QWTmwD/Q/yjxYtaQdahDUufB7NHp1Y0dHSMAfQTccsXVRPm1Z8qBiSveDGrv0eyG/t0mAgcmJQTLULvkh/mTmAUkklaDvUF9S3XKZJxM/xnYppkHNo0EsYoVY1ZFl+Cioi9tgJDXZQrjx6gZupHwSa2SDW5WwPpjgYOhHpFsRh1hRyvGLBWdZ0/lX/w9ByLt+ITN7hWElvLC+yWCfMFHBCduIDDUVGAKCxFymITBaB1oqIfZsMUd4z61jX60K7H2Jr/J0rBxRfC/sIjAMWdzHruE7fzbEau+p1z8ebi0eQDhBVq/ODVpFz3rM9v3NiU77MCC9hDhHZRi2BdPXy5Nqqiha/7y31rvvqCrBgWxHzE6ZEgxSuFEG+dlQn3N9li0lGv0vKk+zI9WYoXVFc3Xe2aYp2rVGa2RYXhuSAUDnWe7KuMvuzebAma63C8r6nIuA0qumJH6JZsrf1MUX2ufdx0ov3PanCrX1/YD0rXWvaVlR6RquLc7ItL5QhaWkhaDbAJfLsuSlo=
dd:
  secure: ctb1nnzFtvhyI+Y3UqCDWUPizVY2Fc63LzCvbjDcQm5aKEL+cYCYZfTbhtPETw1LG2zWFSLkDPpoLJI0ZQxdjLZLIXTAtZvt77mfZ9TPQcOMP6uAKIgpYwIIIuRDYy9kL4t0UTgnCYhe3rV285nfFKXbNY9Ks7tpUzMFdFSag+xeBXguDswGFVOaCOTLlTOsADFtpx0BYbcbkFDu3EPEsDwvxKumxD7P+fS0Zk1dYe+lK5u1KathEM9zdG/0v8b4oLwAonaYMCVAmRP6dgZPjB94oe6AYhpfMxsQjS3Ifbkc1tbgKjmv2PTM+pmzOz5AHBwEzj5amkqZAVa0x6TZyZf1JNEFQAy4cWEt7BKu3WS98R4rf5UaTArTiSlQba3CuS+uWQscWywLaAs7Cu6OxLNUY7Z0YRZ4Y3k7KdPsx1vdQY53PIkETkFvo27gC7lL4uEYaRbMvkLqOKTdq8EnWOsoCMJYdDvyJtzXelfmamz8nIRAc9lQEq/tu8OHlULdMdxCumIrwStgn1Kiuszyx7r8tTI2+1HUz30ZtIIwo5ybUYUCqydl+ZWH9fnFbG78EabPpxMyQDTCc/T5OV99VcNlFdQQraOVnT1pdErM+CG74KKBwhb6rHzpv17y4I9Dk5uH1Kq35b+G+qi77lgIsSSOUYgQKD/xZhu01joz6S0=
